"""Konfigurationsmodelle für den Hexapod."""

from .model import (
    ANALOG_MAX,
    MAX_ANALOG_CHANNEL,
    MIN_CALIBRATION_SPAN,
    BodyConfig,
    CameraAxis,
    CameraDriverConfig,
    CameraServoConfig,
    DriverConfig,
    FootSensorCalibration,
    FootSensorConfig,
    FootSensorsConfig,
    Joint,
    LegConfig,
    LegGeometry,
    LegRow,
    LegServoConfig,
    LegSide,
    RobotConfig,
    ServoConfig,
    ServoLimits,
)

__all__ = [
    "ANALOG_MAX",
    "MAX_ANALOG_CHANNEL",
    "MIN_CALIBRATION_SPAN",
    "BodyConfig",
    "CameraAxis",
    "CameraDriverConfig",
    "CameraServoConfig",
    "DriverConfig",
    "FootSensorCalibration",
    "FootSensorConfig",
    "FootSensorsConfig",
    "Joint",
    "LegConfig",
    "LegGeometry",
    "LegRow",
    "LegServoConfig",
    "LegSide",
    "RobotConfig",
    "ServoConfig",
    "ServoLimits",
]
