"""Konfigurationsmodelle für den Hexapod."""

from .model import (
    ANALOG_CAPABLE_BUS_TYPES,
    ANALOG_MAX,
    DEFAULT_BUS,
    MAX_ANALOG_CHANNEL,
    MIN_CALIBRATION_SPAN,
    BodyConfig,
    BusConfig,
    CameraAxis,
    CameraServoConfig,
    FootSensorCalibration,
    FootSensorConfig,
    FootSensorsConfig,
    Joint,
    LegConfig,
    LegGeometry,
    LegRow,
    LegServoConfig,
    LegSide,
    MaestroBus,
    Pca9685Bus,
    RobotConfig,
    ServoConfig,
    ServoLimits,
    SimulatorBus,
)

__all__ = [
    "ANALOG_CAPABLE_BUS_TYPES",
    "ANALOG_MAX",
    "DEFAULT_BUS",
    "MAX_ANALOG_CHANNEL",
    "MIN_CALIBRATION_SPAN",
    "BodyConfig",
    "BusConfig",
    "CameraAxis",
    "CameraServoConfig",
    "FootSensorCalibration",
    "FootSensorConfig",
    "FootSensorsConfig",
    "Joint",
    "LegConfig",
    "LegGeometry",
    "LegRow",
    "LegServoConfig",
    "LegSide",
    "MaestroBus",
    "Pca9685Bus",
    "RobotConfig",
    "ServoConfig",
    "ServoLimits",
    "SimulatorBus",
]
